#!/bin/bash

if [[ ${VERBOSE} == yes ]]
then
  debug "${YELLOW}[ ${LIME}$(echo $(caller | awk '{print $2}') | awk -F\/ '{print $NF}') ${YELLOW}calls (in line: ${LIME}$(caller | awk '{print $1}')${YELLOW}) ${LIME}$(echo ${BASH_SOURCE} | awk -F\/ '{print $NF}')${YELLOW} ]"
fi

# flush all iptables entries
iptables -t filter -F
iptables -t filter -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t filter -P INPUT ACCEPT
iptables -t filter -P OUTPUT ACCEPT
iptables -t filter -P FORWARD ACCEPT

# initialise chains that will do the work and log the packets
iptables -t mangle -N CONNMARK1
iptables -t mangle -A CONNMARK1 -j MARK --set-mark 1
iptables -t mangle -A CONNMARK1 -j CONNMARK --save-mark
#iptables -t mangle -A CONNMARK1 -j LOG --log-prefix 'iptables-mark1: ' --log-level info

iptables -t mangle -N CONNMARK2
iptables -t mangle -A CONNMARK2 -j MARK --set-mark 2
iptables -t mangle -A CONNMARK2 -j CONNMARK --save-mark
#iptables -t mangle -A CONNMARK2 -j LOG --log-prefix 'iptables-mark2: ' --log-level info

iptables -t mangle -N CONNMARK3
iptables -t mangle -A CONNMARK3 -j MARK --set-mark 3
iptables -t mangle -A CONNMARK3 -j CONNMARK --save-mark
#iptables -t mangle -A CONNMARK3 -j LOG --log-prefix 'iptables-mark3: ' --log-level info

iptables -t mangle -N RESTOREMARK
iptables -t mangle -A RESTOREMARK -j CONNMARK --restore-mark
#iptables -t mangle -A RESTOREMARK -j LOG --log-prefix 'restore-mark: ' --log-level info

iptables -t nat -N SNAT1
if [[ ${VERBOSE} == yes ]]
then
  iptables -t nat -A SNAT1 -j LOG --log-prefix "snat-to-${VPN_SERVER1_LOCALROUTER_IP}: " --log-level info
fi
iptables -t nat -A SNAT1 -j SNAT --to-source ${VPN_SERVER1_LOCALROUTER_IP}

iptables -t nat -N SNAT2
if [[ ${VERBOSE} == yes ]]
then
  iptables -t nat -A SNAT2 -j LOG --log-prefix "snat-to-${VPN_SERVER2_LOCALROUTER_IP}: " --log-level info
fi
iptables -t nat -A SNAT2 -j SNAT --to-source ${VPN_SERVER2_LOCALROUTER_IP}

iptables -t nat -N SNAT3
if [[ ${VERBOSE} == yes ]]
then
  iptables -t nat -A SNAT3 -j LOG --log-prefix "snat-to-${VPN_SERVER3_LOCALROUTER_IP}: " --log-level info
fi
iptables -t nat -A SNAT3 -j SNAT --to-source ${VPN_SERVER3_LOCALROUTER_IP}

# restore the fwmark on packets that belong to an existing connection
iptables -t mangle -A PREROUTING -i ${MAIN_ETH} -p tcp -m state --state ESTABLISHED,RELATED -j RESTOREMARK

# if the mark is zero it means the packet does not belong to an existing connection
iptables -t mangle -A PREROUTING -p tcp -m state --state NEW -m statistic --mode nth --every 3 --packet 0 -j CONNMARK1
iptables -t mangle -A PREROUTING -p tcp -m state --state NEW -m statistic --mode nth --every 3 --packet 1 -j CONNMARK2
iptables -t mangle -A PREROUTING -p tcp -m state --state NEW -m statistic --mode nth --every 3 --packet 2 -j CONNMARK3

iptables -t nat -A POSTROUTING -o ${VPN_SERVER1_DEV} -j SNAT1
iptables -t nat -A POSTROUTING -o ${VPN_SERVER2_DEV} -j SNAT2
iptables -t nat -A POSTROUTING -o ${VPN_SERVER3_DEV} -j SNAT3
